### ISSUE TITLE
Project still active?

### ISSUE THREAD

**Issue by mrbluecoat** [Allow2/c-icap-allow2#1]
Cool project! Still active?

**Comment by macinspak** [comment]
Absolutely! We've been heavily working in the background.
Thanks for your interest.

**Comment by mrbluecoat** [comment]
That's great to hear. I'm happy to beta test.

**Comment by mrbluecoat** [comment]
P.S. Any ETA on the next release? With the last release being 5 years ago, I didn't know if I should wait.

**Comment by macinspak** [comment]
Not in the very near future, and it’s a first integration, so not really a solid implementation. More than welcome to contribute as it’s all opensource

Thanks for your interest!
